name: pnpm ci Workflow
on:
  push:

jobs:
  install-dependencies:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Cheeckout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-nodep@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

  build:
    runs-on: ubuntu-latest
    needs: [install-dependencies] # lint, test 단계가 모두 실행되어야 함
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Cheeckout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Run Build
        run: pnpm run build
